// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Multilinks.ApiService.Data;
using Multilinks.ApiService.Models;
using System;

namespace Multilinks.ApiService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171122111359_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Multilinks.ApiService.Models.EndpointEntity", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Description");

                    b.Property<int>("DirectionCapability");

                    b.Property<bool>("IsCloudConnected");

                    b.Property<bool>("IsGateway");

                    b.Property<string>("Name");

                    b.Property<Guid>("ServiceAreaId");

                    b.HasKey("EndpointId");

                    b.ToTable("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
