// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Multilinks.ApiService.Services;
using System;

namespace Multilinks.ApiService.Services.Migrations
{
    [DbContext(typeof(ApiServiceDbContext))]
    [Migration("20180906085706_ExtendEndpointEntity")]
    partial class ExtendEndpointEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Multilinks.ApiService.Entities.EndpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId");

                    b.Property<string>("ClientType");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Description");

                    b.Property<Guid>("EndpointId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
